### ISSUE TITLE
[LEITOR] gostaria de visualizar a quantidade de citações e fator de impacto em colunas na tabela principal do programa.

### ISSUE THREAD

**Issue by hensou** [Hedanvisa/jabref#4]
- [x] Deve ser adicionado o campo **citações** como parte de uma Entry
- [x] Deve ser adicionado o campo **fator de impacto** como parte de uma Entry
- [x] Deve ser adicionado uma coluna na GUI para visualizar as citações
- [x] Deve ser adicionada uma coluna na GUI para visualizar o fator de impacto

**Comment by saviocamacam** [comment]
Isso foi fechado no commit b692f7e9e24425fa76f1ddf97e656dd89fc147c7
