### ISSUE TITLE
[LEITOR] gostaria de selecionar um ou mais trabalhos para fazer a busca da quantidade de citações.

### ISSUE THREAD

**Issue by hensou** [Hedanvisa/jabref#6]
- [ ] Adicionar outra entrada "Buscar quantidade de citações" no menu de contexto para realizar a busca da quantidade de citações
- [ ] Devem ser adicionados novos EventListeners para a nova entrada ser feita a chamada para a função de busca das citações
- [ ] O valor do campo da Entry deve ser alterado de acordo com a resposta obtida da busca

**Comment by saviocamacam** [comment]
Essa issue foi fechada em 38a31ea12c69b122e69ceb56b2b12d16bf9a29b0
