### ISSUE TITLE
[LEITOR] gostaria de selecionar um ou mais trabalhos para fazer a busca do fator de impacto.

### ISSUE THREAD

**Issue by hensou** [Hedanvisa/jabref#7]
- [x] Adicionar outra entrada "Buscar fator de impacto" no menu de contexto para realizar a busca da quantidade de citações
- [x] Devem ser adicionados novos EventListeners para a nova entrada ser feita a chamada para a função de busca das citações
- [x] O valor do campo da Entry deve ser alterado de acordo com a resposta obtida da busca
- [x] Se o valor "journal/booktitle" não exisitir, deve exibir um dialog com a mensagem "
Can not search. Journal/Booktitle unavailable." e busca não deve ser feita.

**Comment by saviocamacam** [comment]
"Se o valor "journal/booktitle" não exisitir, deve exibir um dialog com a mensagem "
Can not search. Journal/Booktitle unavailable." e busca não deve ser feita." É marcado pelo commit f0c3f3ed5e7d3a45e093bd84f5df5b624b7a1aca

**Comment by saviocamacam** [comment]
fechado pelo commit f0c3f3ed5e7d3a45e093bd84f5df5b624b7a1aca

**Comment by saviocamacam** [comment]
fechado pelo commit f0c3f3ed5e7d3a45e093bd84f5df5b624b7a1aca
